name: Compilar y desplegar

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**'

env:
  VERSION_DOTNET: '9.0.x'
  AZURE_APP_SERVICE_NOMBRE: BibliotecaAPI20260202115934
  AZURE_APP_SERVICE_UBICACION_PAQUETE: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROYECTO: BibliotecaAPI.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.VERSION_DOTNET }}

      - name: Obteniendo las dependencias
        run: dotnet restore ${{ env.PROYECTO }}

      - name: Compilar
        run: dotnet build ${{ env.PROYECTO }} --configuration Release --no-restore

      # - name: Realizar pruebas
      #   run: dotnet test --configuration Release --no-build

      - name: Publicar el Web API
        run: dotnet publish ${{ env.PROYECTO }} -c Release -o miapp

      - name: Cargar Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./miapp

  despliegue:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Obtener los artefactos
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Despliegue al Azure App Service
        uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NOMBRE }}
          publish-profile: ${{ secrets.AZURE_PERFIL_PUBLICO }}
          package: ${{ env.AZURE_APP_SERVICE_UBICACION_PAQUETE }}
