name: Hola mundo

on:
  workflow_dispatch: # ejecución manual
# push:
#    branches:
#      - main
#    paths:
#      - '**'
#  pull_request:
#    branches:
#      - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Muestra mensaje hola mundo
        run: echo "hola mundo, Nicolás"

      - name: Listar los archivos del repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos:"
          ls -la
          tree || true
